export const it_qwerty = [
  [
    { k: "\\|" },
    { k: "1!" },
    { k: '2"' },
    { k: "3£" },
    { k: "4$" },
    { k: "5%" },
    { k: "6&" },
    { k: "7/" },
    { k: "8(" },
    { k: "9)" },
    { k: "0=" },
    { k: "'?" },
    { k: "ì^" },
    { k: "Backspace", size: 2 },
  ],
  [
    { k: "Tab", size: 1.5 },
    { k: "qQ" },
    { k: "wW" },
    { k: "eE" },
    { k: "rR" },
    { k: "tT" },
    { k: "yY" },
    { k: "uU" },
    { k: "iI" },
    { k: "oO" },
    { k: "pP" },
    { k: "èé[{" },
    { k: "+*]}" },
    { k: "Enter", size: 1.5 },
  ],
  [
    { k: "CapsLock", size: 1.75 },
    { k: "aA" },
    { k: "sS" },
    { k: "dD" },
    { k: "fF" },
    { k: "gG" },
    { k: "hH" },
    { k: "jJ" },
    { k: "kK" },
    { k: "lL" },
    { k: "òç@" },
    { k: "à°#" },
    { k: `ù§` },
    { k: "Enter", size: 1.25 },
  ],
  [
    { k: "ShiftLeft", size: 1.25 },
    { k: "><" },
    { k: "zZ" },
    { k: "xX" },
    { k: "cC" },
    { k: "vV" },
    { k: "bB" },
    { k: "nN" },
    { k: "mM" },
    { k: ",;" },
    { k: ".:" },
    { k: "-_" },
    { k: "ShiftRight", size: 2.75 },
  ],
  [
    { k: "ControlLeft", size: 1.25 },
    { k: "MetaLeft", size: 1.25 },
    { k: "AltLeft", size: 1.25 },
    { k: "Space", size: 6.25 },
    { k: "AltRight", size: 1.25 },
    { k: "MetaRight", size: 1.25 },
    { k: "Option", size: 1.25 },
    { k: "ControlRight", size: 1.25 },
  ],
];
